#!/usr/bin/env python3
"""Phase 3, step 3: turn captured handshakes into the transport report.

Reads phase3/transport.json (measured) and writes phase3/TRANSPORT.md.

The congestion-window section is COMPUTED, not measured, and says so. Segment
counts come from measured flight bytes divided by a stated MSS. This host has
segmentation offload enabled on every interface and no passwordless sudo to
disable it, so any segment count read off a capture here would be an artifact of
offload rather than a property of the handshake. Dividing measured bytes by a
stated MSS is the honest version of the same question.

Run:  python3 phase3/report.py
"""
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "phase3" / "transport.json"
OUT = ROOT / "phase3" / "TRANSPORT.md"

# RFC 6928 raised the initial congestion window to 10 segments; that is the
# default on Linux and the value worth testing against.
IW = 10
# 1460 = 1500 Ethernet MTU - 20 IPv4 - 20 TCP. 1360 is a common effective MSS
# once a tunnel or VPN is in the path, included as a sensitivity check.
MSS = {"ethernet-1460": 1460, "tunnelled-1360": 1360}
# TLS 1.3 fragments handshake messages into records at 2^14 bytes of plaintext.
RECORD_LIMIT = 16384


def main() -> None:
    rows = [r for r in json.loads(SRC.read_text())
            if r.get("mode") == "no-compression" and "error" not in r]
    rows.sort(key=lambda r: r["server_flight_handshake_bytes"])

    md = [
        "# Transport: what a post-quantum handshake puts on the wire",
        "",
        "Generated by `phase3/report.py` from `phase3/transport.json`; do not",
        "hand-edit. Captures come from `phase3/transport.py`, decrypted with a TLS",
        "key log so every handshake message can be attributed. Server and client are",
        "both OpenSSL 3.5.5. Raw captures in `phase3/evidence/<chain>/`.",
        "",
        "## Measured: handshake message bytes",
        "",
        "| Chain | ClientHello | Certificate | CertificateVerify | Server flight | Largest record |",
        "|---|---|---|---|---|---|",
    ]
    for r in rows:
        s, c = r["server_messages"], r["client_messages"]
        md.append(
            f"| {r['chain']} | {c.get('ClientHello', 0):,} | "
            f"{s.get('Certificate', 0):,} | {s.get('CertificateVerify', 0):,} | "
            f"{r['server_flight_handshake_bytes']:,} | {r['largest_server_record']:,} |"
        )

    biggest = max(rows, key=lambda r: r["largest_server_record"])
    md += [
        "",
        "\"Server flight\" is every handshake message the server sends before the",
        "client's Finished, so it excludes NewSessionTicket, which arrives after.",
        "",
        f"No chain fragments across TLS records. The largest record measured is",
        f"{biggest['largest_server_record']:,} bytes ({biggest['chain']}) against the",
        f"{RECORD_LIMIT:,}-byte plaintext ceiling, leaving about",
        f"{RECORD_LIMIT - biggest['largest_server_record']:,} bytes of headroom. A third",
        "certificate in the chain, or a wider SAN list, crosses it.",
        "",
        "## Computed: does the server's first flight fit the initial congestion window?",
        "",
        f"Segments are measured flight bytes divided by MSS, against an initial",
        f"congestion window of {IW} segments (RFC 6928). **Computed, not measured:**",
        "see the note in `report.py` about segmentation offload on this host.",
        "A flight that exceeds the window waits for the client to acknowledge the",
        "first burst before the rest can be sent, which costs an extra round trip",
        "before the handshake completes.",
        "",
        "| Chain | Flight bytes | " + " | ".join(
            f"Segments @ {v}" for v in MSS.values()) + " | Fits IW10 |",
        "|---|---|" + "---|" * (len(MSS) + 1),
    ]
    for r in rows:
        f = r["server_flight_handshake_bytes"]
        segs = {k: math.ceil(f / v) for k, v in MSS.items()}
        fits = "yes" if all(s <= IW for s in segs.values()) else (
            "no" if all(s > IW for s in segs.values()) else "borderline")
        md.append(f"| {r['chain']} | {f:,} | " +
                  " | ".join(str(segs[k]) for k in MSS) + f" | {fits} |")

    fitting = [r for r in rows
               if math.ceil(r["server_flight_handshake_bytes"] / 1460) <= IW]
    md += [
        "",
        f"At the standard 1460-byte MSS the window holds {IW * 1460:,} bytes. "
        f"The heaviest chain that still fits is **{fitting[-1]['chain']}** at "
        f"{fitting[-1]['server_flight_handshake_bytes']:,} bytes; everything above it "
        "pays an extra round trip on every full handshake.",
        "",
        "## Reproduce",
        "",
        "```",
        "python3 phase3/transport.py   # captures, needs dumpcap + the wireshark group",
        "python3 phase3/report.py      # regenerates this file from transport.json",
        "```",
    ]
    OUT.write_text("\n".join(md) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)} from {len(rows)} captures")
    for r in rows:
        f = r["server_flight_handshake_bytes"]
        print(f"  {r['chain']:10s} flight={f:6,d} segs@1460={math.ceil(f/1460):3d} "
              f"{'fits' if math.ceil(f/1460) <= IW else 'EXCEEDS'} IW{IW}")


if __name__ == "__main__":
    main()
